name: deepsphere
channels:
  - conda-forge
  - defaults
dependencies:
  - asn1crypto=0.24.0
  - astropy=3.1.2
  - atomicwrites=1.3.0
  - attrs=18.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.5
  - ca-certificates=2019.6.16
  - cartopy=0.17.0
  - certifi=2019.6.16
  - cffi=1.12.3
  - chardet=3.0.4
  - cryptography=2.5
  - cycler=0.10.0
  - dbus=1.13.0
  - embree=2.14.0
  - expat=2.2.5
  - fontconfig=2.13.0
  - freetype=2.8.1
  - geos=3.7.1
  - gettext=0.19.8.1
  - glib=2.56.2
  - gst-plugins-base=1.12.5
  - gstreamer=1.12.5
  - healpy=1.11.0
  - icu=58.2
  - idna=2.8
  - jpeg=9c
  - kiwisolver=1.0.1
  - libffi=3.2.1
  - libgcc-ng=7.3.0
  - libgfortran-ng=7.2.0
  - libiconv=1.15
  - libpng=1.6.34
  - libspatialindex=1.8.5
  - libstdcxx-ng=7.3.0
  - libtiff=4.0.10
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.8
  - libxslt=1.1.32
  - lxml=4.3.3
  - matplotlib=2.2.0
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - more-itertools=4.3.0
  - ncurses=6.1
  - olefile=0.46
  - openssl=1.0.2r
  - owslib=0.17.1
  - pcre=8.41
  - pillow=5.2.0
  - pip=19.0.3
  - pluggy=0.9.0
  - proj4=5.2.0
  - psutil=5.5.1
  - pthread-stubs=0.4
  - py=1.8.0
  - pycparser=2.19
  - pyembree=0.1.5
  - pyepsg=0.4.0
  - pykdtree=1.3.1
  - pyopenssl=19.0.0
  - pyparsing=2.3.1
  - pyproj=1.9.6
  - pyqt=5.6.0
  - pyshp=2.1.0
  - pysocks=1.6.8
  - pytest=4.3.0
  - pytest-arraydiff=0.3
  - pytest-astropy=0.4.0
  - pytest-doctestplus=0.1.3
  - pytest-openfiles=0.3.1
  - pytest-remotedata=0.3.1
  - pytest-runner=4.4
  - python=3.6.7
  - python-dateutil=2.8.0
  - pytz=2018.9
  - qt=5.6.2
  - readline=7.0
  - requests=2.21.0
  - rtree=0.8.3
  - setuptools=40.8.0
  - shapely=1.6.4
  - sip=4.18.1
  - six=1.12.0
  - sqlite=3.26.0
  - tk=8.6.9
  - tornado=5.1.1
  - urllib3=1.24.2
  - wheel=0.33.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.2
  - xz=5.2.4
  - zlib=1.2.11
  - blas=1.0
  - cudatoolkit=9.0
  - intel-openmp=2019.1
  - mkl=2019.1
  - numpy=1.15.4
  - numpy-base=1.15.4
  - scipy=1.2.1
  - pip:
    - absl-py==0.1.11
    - astor==0.6.2
    - bleach==1.5.0
    - colorlog==4.0.2
    - decorator==4.3.2
    - entrypoints==0.2.3
    - future==0.17.1
    - gast==0.2.0
    - google-pasta==0.1.7
    - grpcio==1.10.0
    - h5py==2.9.0
    - html5lib==0.9999999
    - ipykernel==4.8.2
    - ipython==6.2.1
    - ipython-genutils==0.2.0
    - jedi==0.11.1
    - jinja2==2.10
    - jsonschema==2.6.0
    - jupyter-client==5.2.2
    - jupyter-core==4.4.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - markdown==2.6.11
    - markupsafe==1.0
    - mistune==0.8.3
    - mpmath==1.1.0
    - msgpack==0.6.1
    - nbconvert==5.3.1
    - nbformat==4.4.0
    - networkx==2.2
    - notebook==5.4.0
    - pandas==0.24.2
    - pandocfilters==1.4.2
    - parso==0.1.1
    - pexpect==4.4.0
    - pickleshare==0.7.4
    - prompt-toolkit==1.0.15
    - protobuf==3.6.1
    - ptyprocess==0.6.0
    - pycollada==0.6
    - pyevtk==1.1.1
    - pyglet==1.3.2
    - pygments==2.2.0
    - git+https://github.com/Droxef/pygsp.git@new_sphere_graph
    - pynvrtc==9.2
    - pyyaml==5.1
    - pyzmq==17.0.0
    - scikit-learn==0.19.1
    - send2trash==1.5.0
    - simplegeneric==0.8.1
    - svg.path==3.0
    - svgutils==0.3.1
    - sympy==1.3
    - tensorboard==1.10.0
    - tensorflow-gpu==1.10.0
    - termcolor==1.1.0
    - terminado==0.8.1
    - testpath==0.3.1
    - tqdm==4.19.6
    - traitlets==4.3.2
    - trimesh==2.37.2
    - wcwidth==0.1.7
    - werkzeug==0.14.1
    - wrapt==1.11.2
    - xxhash==1.3.0
